### PR TITLE
File-cleanup

### PR DESCRIPTION
**Pull request by kallewesterling**
### Summary

I have cleaned up a little bit in the repository's files to make it look a bit cleaner.

### Describe your changes

- [X] Removed `pre-commit` as we were not using it (we should?)
- [X] Removed `ruff` as we were not using it (we should)
- [X] moved the ways_of_working.md into the documentation, made it a RST
- [X] as a consequence of the above, I also added `spinxemoji` to be able to render one of the emoji's in the documentation.

### CODE REVIEW

**Comment by rwood-97** [comment]
On deleting pre-commit/ruff files, I use both when making my commits. 
To set up, cd to MapReader then do `pre-commit install` and it will install the hooks.

We should probably add this to contribution docs.

**Comment by kallewesterling** [comment]
Ah, I didn't know! There was no mention of it, so maybe I'll just add that as a separate issue.

**Comment by kallewesterling** [comment]
Added: https://github.com/Living-with-machines/MapReader/issues/453

**Comment by kallewesterling** [comment]
I lifted those files back @rwood-97.

**Comment by rwood-97** [comment]
Great, thanks! Looks good

**Pull request merged**
