### PR TITLE
Adding in dates and links to upcoming community calls

### PR DESCRIPTION
**Pull request by kallewesterling**
### Summary

Adds in the new dates for community calls to the documentation.

### Describe your changes

I have added the dates.

### Checklist before assigning a reviewer (update as needed)

- [X] Update relevant docs

### Reviewer checklist

Please add anything you want reviewers to specifically focus/comment on.

- [ ] Everything looks ok?

### CODE REVIEW

**Comment by kallewesterling** [comment]
@rwood-97 FYI this is pending because I'm still waiting for IT to let me know if we can host the notetaking documents on Sharepoint (for safer storage).

**Comment by kallewesterling** [comment]
@rwood-97 heard back from IT that there are no other solutions. I've chatted to the TPS team about this, and they are all in agreement that we should keep doing Google Docs, but then maybe transfer to a different storage after the Community Calls...

**Comment by kallewesterling** [comment]
I'll do the following now:
- [ ] add in Google Docs links to each upcoming month
- [ ] open the PR for review (should be an easy one)

Then let's merge.

**Comment by kallewesterling** [comment]
@kmcdono2 FYI

**Comment by kallewesterling** [comment]
Ready for review!

**Review by rwood-97 — APPROVED** [review]
Looks good :):)

**Comment by kallewesterling** [comment]
thank you!

**Pull request merged**
