### PR TITLE
print to logger

### PR DESCRIPTION
**Pull request by rwood-97**

### CODE REVIEW

**Comment by rwood-97** [comment]
@kallewesterling let me know about merging this into your branch. Will review yours after

**Comment by kallewesterling** [comment]
@rwood-97 Can't remember what we said about this one but I think we should just go ahead and merge the two of them, right?

**Comment by rwood-97** [comment]
Ah wait no, some of the messages are actually warnings and some are info. So both being debug seems confusing. 
Maybe I'll merge it and we can work out from the other branch?

**Comment by kallewesterling** [comment]
> Ah wait no, some of the messages are actually warnings and some are info. So both being debug seems confusing. Maybe I'll merge it and we can work out from the other branch?

SOrry - only now saw this! Yeah, let's merge this and then we'll do any further edits on the other branch.

**Pull request merged**
